name: Build
on:
  pull_request:
    branches: [main]
jobs:
  build-api:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: api
          load: true
          cache-from: type=gha,scope=api
          cache-to: type=gha,mode=max,scope=api
          tags: ${{ env.DOCKER_IMAGE }}
      - name: Run lint-check
        run: |
          docker run --name lint-check $DOCKER_IMAGE make lint-check-ci
          docker cp lint-check:/app/lint-check-results.json ./lint-check-results.json
      - name: Upload lint-check results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./lint-check-results.json
          check-name: lint-check
          fail-on-error: false
      - name: Run type-check
        run: |
          docker run --name type-check $DOCKER_IMAGE make type-check-ci
          docker cp type-check:/app/type-check-results.json ./type-check-results.json
      - name: Upload type-check results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./type-check-results.json
          check-name: type-check
          fail-on-error: false
      # - name: Run security-check
      #   run: |
      #     docker run --name security-check $DOCKER_IMAGE make security-check-ci
      #     docker cp security-check:/app/security-check-results.json ./security-check-results.json
      # - name: Upload security-check results
      #   uses: kibalabs/github-action-create-annotations@main
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     json-file-path: ./security-check-results.json
      #     check-name: security-check
      #     fail-on-error: false
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    env:
      DOCKER_IMAGE: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --tag $DOCKER_IMAGE .
      - name: Run linting
        run: |
          docker run --name linting $DOCKER_IMAGE lint --directory pablo --output-file linting-results.json --output-format annotations
          docker cp linting:/app/linting-results.json ./linting-results.json
      - name: Upload linting results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./client/linting-results.json
          check-name: lint-client
          fail-on-error: false
