name: Build
on:
  pull_request:
    branches: [main]
jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      DOCKER_IMAGE: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --tag $DOCKER_IMAGE .
      - name: Run linting
        run: |
          docker run --name linting $DOCKER_IMAGE lint --directory pablo --output-file linting-results.json --output-format annotations
          docker cp linting:/app/linting-results.json ./linting-results.json
      - name: Upload linting results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./api/linting-results.json
          check-name: lint-api
          fail-on-error: false
